/* tslint:disable */
/* eslint-disable */
/**
 * Applicativo BFF
 * Strato applicativo tramite il quale si fa interfacciare i vari microservizi BE con l\'applicativo FE
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.calo29@studenti.uniba.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CartellaParams } from '../model';
// @ts-ignore
import type { GenericResponseDtoCartelleDto } from '../model';
// @ts-ignore
import type { GenericResponseDtoListCartelleDto } from '../model';
// @ts-ignore
import type { GenericResponseDtoString } from '../model';
// @ts-ignore
import type { ModificaCartellaParams } from '../model';
/**
 * GestioneDelleCartelleApi - axios parameter creator
 * @export
 */
export const GestioneDelleCartelleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Se la cartella esiste già, questo endpoint si occupa del salvataggio nel db.
         * @summary Aggiunta di una cartella nel db già creata
         * @param {CartellaParams} cartellaParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aggiungiCartella: async (cartellaParams: CartellaParams, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cartellaParams' is not null or undefined
            assertParamExists('aggiungiCartella', 'cartellaParams', cartellaParams)
            const localVarPath = `/cartelle-management/cartella/aggiungi`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cartellaParams, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creazione delle cartelle di addestramento dei relativi bot
         * @summary Creazione della cartella
         * @param {CartellaParams} cartellaParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        creaCartella: async (cartellaParams: CartellaParams, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cartellaParams' is not null or undefined
            assertParamExists('creaCartella', 'cartellaParams', cartellaParams)
            const localVarPath = `/cartelle-management/cartella/crea`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cartellaParams, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Elenco delle cartelle presenti nel db
         * @summary Elenco cartelle
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        elencoCartelle: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cartelle-management/cartella/elenco`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Eliminare una cartella cartella e i file contenuti in essa
         * @summary Eliminare una cartella cartella
         * @param {CartellaParams} cartellaParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eliminaCartella: async (cartellaParams: CartellaParams, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cartellaParams' is not null or undefined
            assertParamExists('eliminaCartella', 'cartellaParams', cartellaParams)
            const localVarPath = `/cartelle-management/cartella/elimina`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (cartellaParams !== undefined) {
                for (const [key, value] of Object.entries(cartellaParams)) {
                    localVarQueryParameter[key] = value;
                }
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Filtrare una cartella nel db
         * @summary Ritrovamento di una cartella
         * @param {CartellaParams} cartellaParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findCartella: async (cartellaParams: CartellaParams, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cartellaParams' is not null or undefined
            assertParamExists('findCartella', 'cartellaParams', cartellaParams)
            const localVarPath = `/cartelle-management/cartella/find`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (cartellaParams !== undefined) {
                for (const [key, value] of Object.entries(cartellaParams)) {
                    localVarQueryParameter[key] = value;
                }
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Rinominare una cartella cartella e aggiornare i path dei file contenuti in essa
         * @summary Rinominare una cartella cartella
         * @param {ModificaCartellaParams} modificaCartellaParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rinominaCartella: async (modificaCartellaParams: ModificaCartellaParams, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modificaCartellaParams' is not null or undefined
            assertParamExists('rinominaCartella', 'modificaCartellaParams', modificaCartellaParams)
            const localVarPath = `/cartelle-management/cartella/rinomina`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modificaCartellaParams, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GestioneDelleCartelleApi - functional programming interface
 * @export
 */
export const GestioneDelleCartelleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GestioneDelleCartelleApiAxiosParamCreator(configuration)
    return {
        /**
         * Se la cartella esiste già, questo endpoint si occupa del salvataggio nel db.
         * @summary Aggiunta di una cartella nel db già creata
         * @param {CartellaParams} cartellaParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aggiungiCartella(cartellaParams: CartellaParams, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericResponseDtoCartelleDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aggiungiCartella(cartellaParams, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GestioneDelleCartelleApi.aggiungiCartella']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creazione delle cartelle di addestramento dei relativi bot
         * @summary Creazione della cartella
         * @param {CartellaParams} cartellaParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async creaCartella(cartellaParams: CartellaParams, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericResponseDtoCartelleDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.creaCartella(cartellaParams, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GestioneDelleCartelleApi.creaCartella']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Elenco delle cartelle presenti nel db
         * @summary Elenco cartelle
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async elencoCartelle(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericResponseDtoListCartelleDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.elencoCartelle(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GestioneDelleCartelleApi.elencoCartelle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Eliminare una cartella cartella e i file contenuti in essa
         * @summary Eliminare una cartella cartella
         * @param {CartellaParams} cartellaParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async eliminaCartella(cartellaParams: CartellaParams, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericResponseDtoString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.eliminaCartella(cartellaParams, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GestioneDelleCartelleApi.eliminaCartella']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Filtrare una cartella nel db
         * @summary Ritrovamento di una cartella
         * @param {CartellaParams} cartellaParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findCartella(cartellaParams: CartellaParams, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericResponseDtoCartelleDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findCartella(cartellaParams, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GestioneDelleCartelleApi.findCartella']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Rinominare una cartella cartella e aggiornare i path dei file contenuti in essa
         * @summary Rinominare una cartella cartella
         * @param {ModificaCartellaParams} modificaCartellaParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rinominaCartella(modificaCartellaParams: ModificaCartellaParams, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericResponseDtoCartelleDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rinominaCartella(modificaCartellaParams, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GestioneDelleCartelleApi.rinominaCartella']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GestioneDelleCartelleApi - factory interface
 * @export
 */
export const GestioneDelleCartelleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GestioneDelleCartelleApiFp(configuration)
    return {
        /**
         * Se la cartella esiste già, questo endpoint si occupa del salvataggio nel db.
         * @summary Aggiunta di una cartella nel db già creata
         * @param {GestioneDelleCartelleApiAggiungiCartellaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aggiungiCartella(requestParameters: GestioneDelleCartelleApiAggiungiCartellaRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericResponseDtoCartelleDto> {
            return localVarFp.aggiungiCartella(requestParameters.cartellaParams, options).then((request) => request(axios, basePath));
        },
        /**
         * Creazione delle cartelle di addestramento dei relativi bot
         * @summary Creazione della cartella
         * @param {GestioneDelleCartelleApiCreaCartellaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        creaCartella(requestParameters: GestioneDelleCartelleApiCreaCartellaRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericResponseDtoCartelleDto> {
            return localVarFp.creaCartella(requestParameters.cartellaParams, options).then((request) => request(axios, basePath));
        },
        /**
         * Elenco delle cartelle presenti nel db
         * @summary Elenco cartelle
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        elencoCartelle(options?: RawAxiosRequestConfig): AxiosPromise<GenericResponseDtoListCartelleDto> {
            return localVarFp.elencoCartelle(options).then((request) => request(axios, basePath));
        },
        /**
         * Eliminare una cartella cartella e i file contenuti in essa
         * @summary Eliminare una cartella cartella
         * @param {GestioneDelleCartelleApiEliminaCartellaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eliminaCartella(requestParameters: GestioneDelleCartelleApiEliminaCartellaRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericResponseDtoString> {
            return localVarFp.eliminaCartella(requestParameters.cartellaParams, options).then((request) => request(axios, basePath));
        },
        /**
         * Filtrare una cartella nel db
         * @summary Ritrovamento di una cartella
         * @param {GestioneDelleCartelleApiFindCartellaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findCartella(requestParameters: GestioneDelleCartelleApiFindCartellaRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericResponseDtoCartelleDto> {
            return localVarFp.findCartella(requestParameters.cartellaParams, options).then((request) => request(axios, basePath));
        },
        /**
         * Rinominare una cartella cartella e aggiornare i path dei file contenuti in essa
         * @summary Rinominare una cartella cartella
         * @param {GestioneDelleCartelleApiRinominaCartellaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rinominaCartella(requestParameters: GestioneDelleCartelleApiRinominaCartellaRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericResponseDtoCartelleDto> {
            return localVarFp.rinominaCartella(requestParameters.modificaCartellaParams, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for aggiungiCartella operation in GestioneDelleCartelleApi.
 * @export
 * @interface GestioneDelleCartelleApiAggiungiCartellaRequest
 */
export interface GestioneDelleCartelleApiAggiungiCartellaRequest {
    /**
     * 
     * @type {CartellaParams}
     * @memberof GestioneDelleCartelleApiAggiungiCartella
     */
    readonly cartellaParams: CartellaParams
}

/**
 * Request parameters for creaCartella operation in GestioneDelleCartelleApi.
 * @export
 * @interface GestioneDelleCartelleApiCreaCartellaRequest
 */
export interface GestioneDelleCartelleApiCreaCartellaRequest {
    /**
     * 
     * @type {CartellaParams}
     * @memberof GestioneDelleCartelleApiCreaCartella
     */
    readonly cartellaParams: CartellaParams
}

/**
 * Request parameters for eliminaCartella operation in GestioneDelleCartelleApi.
 * @export
 * @interface GestioneDelleCartelleApiEliminaCartellaRequest
 */
export interface GestioneDelleCartelleApiEliminaCartellaRequest {
    /**
     * 
     * @type {CartellaParams}
     * @memberof GestioneDelleCartelleApiEliminaCartella
     */
    readonly cartellaParams: CartellaParams
}

/**
 * Request parameters for findCartella operation in GestioneDelleCartelleApi.
 * @export
 * @interface GestioneDelleCartelleApiFindCartellaRequest
 */
export interface GestioneDelleCartelleApiFindCartellaRequest {
    /**
     * 
     * @type {CartellaParams}
     * @memberof GestioneDelleCartelleApiFindCartella
     */
    readonly cartellaParams: CartellaParams
}

/**
 * Request parameters for rinominaCartella operation in GestioneDelleCartelleApi.
 * @export
 * @interface GestioneDelleCartelleApiRinominaCartellaRequest
 */
export interface GestioneDelleCartelleApiRinominaCartellaRequest {
    /**
     * 
     * @type {ModificaCartellaParams}
     * @memberof GestioneDelleCartelleApiRinominaCartella
     */
    readonly modificaCartellaParams: ModificaCartellaParams
}

/**
 * GestioneDelleCartelleApi - object-oriented interface
 * @export
 * @class GestioneDelleCartelleApi
 * @extends {BaseAPI}
 */
export class GestioneDelleCartelleApi extends BaseAPI {
    /**
     * Se la cartella esiste già, questo endpoint si occupa del salvataggio nel db.
     * @summary Aggiunta di una cartella nel db già creata
     * @param {GestioneDelleCartelleApiAggiungiCartellaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GestioneDelleCartelleApi
     */
    public aggiungiCartella(requestParameters: GestioneDelleCartelleApiAggiungiCartellaRequest, options?: RawAxiosRequestConfig) {
        return GestioneDelleCartelleApiFp(this.configuration).aggiungiCartella(requestParameters.cartellaParams, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creazione delle cartelle di addestramento dei relativi bot
     * @summary Creazione della cartella
     * @param {GestioneDelleCartelleApiCreaCartellaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GestioneDelleCartelleApi
     */
    public creaCartella(requestParameters: GestioneDelleCartelleApiCreaCartellaRequest, options?: RawAxiosRequestConfig) {
        return GestioneDelleCartelleApiFp(this.configuration).creaCartella(requestParameters.cartellaParams, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Elenco delle cartelle presenti nel db
     * @summary Elenco cartelle
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GestioneDelleCartelleApi
     */
    public elencoCartelle(options?: RawAxiosRequestConfig) {
        return GestioneDelleCartelleApiFp(this.configuration).elencoCartelle(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Eliminare una cartella cartella e i file contenuti in essa
     * @summary Eliminare una cartella cartella
     * @param {GestioneDelleCartelleApiEliminaCartellaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GestioneDelleCartelleApi
     */
    public eliminaCartella(requestParameters: GestioneDelleCartelleApiEliminaCartellaRequest, options?: RawAxiosRequestConfig) {
        return GestioneDelleCartelleApiFp(this.configuration).eliminaCartella(requestParameters.cartellaParams, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Filtrare una cartella nel db
     * @summary Ritrovamento di una cartella
     * @param {GestioneDelleCartelleApiFindCartellaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GestioneDelleCartelleApi
     */
    public findCartella(requestParameters: GestioneDelleCartelleApiFindCartellaRequest, options?: RawAxiosRequestConfig) {
        return GestioneDelleCartelleApiFp(this.configuration).findCartella(requestParameters.cartellaParams, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Rinominare una cartella cartella e aggiornare i path dei file contenuti in essa
     * @summary Rinominare una cartella cartella
     * @param {GestioneDelleCartelleApiRinominaCartellaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GestioneDelleCartelleApi
     */
    public rinominaCartella(requestParameters: GestioneDelleCartelleApiRinominaCartellaRequest, options?: RawAxiosRequestConfig) {
        return GestioneDelleCartelleApiFp(this.configuration).rinominaCartella(requestParameters.modificaCartellaParams, options).then((request) => request(this.axios, this.basePath));
    }
}

