openapi: 3.0.1
info:
  title: Applicativo Bot Alimentazione
  description: Ms che contiene tutti i path per comunicare con il bot addestrato sull'alimentazione
  contact:
    name: Federico Calò (matricola 678191)
    url: https://www.federicocalo.dev
    email: f.calo29@studenti.uniba.it
  version: 1.0.0
servers:
  - url: http://localhost:8084
    description: Ambiente locale
tags:
  - name: Bot Alimentazione Chat Controller
    description: Gestione della chat
paths:
  /bot-alimentazione-chat/normal-chat:
    get:
      tags:
        - Bot Alimentazione Chat Controller
      summary: Chat normale
      description: Invio di un messaggio al bot Alimentazione sfruttando l'LLM non addestrato
      operationId: normalChat
      parameters:
        - name: messagge
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoResponseNormalMessageDto'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoResponseNormalMessageDto'
  /bot-alimentazione-chat/evaluete-normal-chat:
    get:
      tags:
        - Bot Alimentazione Chat Controller
      summary: Chat Valutazione pdf
      description: Chat Valutazione pdf
      operationId: evalueteNormalChat
      parameters:
        - name: messagge
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoResponseEvalueteNormalChatDto'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoResponseEvalueteNormalChatDto'
  /bot-alimentazione-chat/chat-addestrata:
    get:
      tags:
        - Bot Alimentazione Chat Controller
      summary: Chat addestrata
      description: Invio di un messaggio al bot Alimentazione sfruttando l'LLM addestrato
      operationId: chatAddestrata
      parameters:
        - name: messagge
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoResponseMessagePdfDto'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoResponseMessagePdfDto'
components:
  schemas:
    Esito:
      type: object
      properties:
        codRet:
          type: string
          enum:
            - OK
            - WARNING
            - KO
        operationId:
          type: string
        messaggi:
          type: array
          items:
            $ref: '#/components/schemas/Messaggio'
    GenericResponseDtoResponseNormalMessageDto:
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/Esito'
        payload:
          $ref: '#/components/schemas/ResponseNormalMessageDto'
    Messaggio:
      type: object
      properties:
        severita:
          type: string
          enum:
            - INFO
            - WARNING
            - ERROR
            - PROPAGATED
        codMsg:
          type: string
        parametri:
          type: array
          items:
            $ref: '#/components/schemas/Parametro'
    Parametro:
      type: object
      properties:
        nome:
          type: string
        valore:
          type: string
    ResponseNormalMessageDto:
      type: object
      properties:
        query:
          type: string
        message:
          type: string
    GenericResponseDtoResponseEvalueteNormalChatDto:
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/Esito'
        payload:
          $ref: '#/components/schemas/ResponseEvalueteNormalChatDto'
    ResponseEvalueteNormalChatDto:
      type: object
      properties:
        query:
          type: string
        answer:
          type: string
        similarity:
          type: string
        sources:
          type: array
          items:
            $ref: '#/components/schemas/SourceDto'
    SourceDto:
      type: object
      properties:
        pageContent:
          type: string
        source:
          type: string
    GenericResponseDtoResponseMessagePdfDto:
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/Esito'
        payload:
          $ref: '#/components/schemas/ResponseMessagePdfDto'
    ResponseMessagePdfDto:
      type: object
      properties:
        query:
          type: string
        answer:
          type: string
        sources:
          type: array
          items:
            $ref: '#/components/schemas/SourceDto'
