openapi: 3.0.1
info:
  title: MS File Management
  description: Microservizio dedicato alla gestione dei documenti e delle cartelle per l'addestramento dei bot
  contact:
    name: Federico Calò (matricola 678191)
    url: https://www.federicocalo.dev
    email: f.calo29@studenti.uniba.it
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Ambiente locale
tags:
  - name: Cartelle Controller
    description: Gestione delle cartelle
  - name: Documenti Controller
    description: Gestione dei documenti
  - name: Rag bot Controller
    description: Gestione dei bot rag
paths:
  /cartelle/crea:
    put:
      tags:
        - Cartelle Controller
      summary: Creazione della cartella
      description: Creazione delle cartelle di addestramento dei relativi bot
      operationId: creaCartella
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartellaParams'
        required: true
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoCartelleDto'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoCartelleDto'
  /cartelle/aggiungi:
    put:
      tags:
        - Cartelle Controller
      summary: Aggiunta di una cartella nel db già creata
      description: Se la cartella esiste già, questo endpoint si occupa del salvataggio nel db.
      operationId: aggiungiCartella
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartellaParams'
        required: true
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoCartelleDto'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoCartelleDto'
  /ragbot/registra:
    post:
      tags:
        - Rag bot Controller
      summary: Registra bot
      description: Registrazione di un bot all'interno del database
      operationId: registraBot
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistraBotParams'
        required: true
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoRagBotPdfDto'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoRagBotPdfDto'
  /ragbot/modifica:
    post:
      tags:
        - Rag bot Controller
      summary: Modifica bot
      description: Modifica le informazioni del bot registrate nel database
      operationId: modificaBot
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModificaBotParams'
        required: true
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoRagBotPdfDto'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoRagBotPdfDto'
  /documenti/addestramento-singolo:
    post:
      tags:
        - Documenti Controller
      summary: Addestamento bot singolo file
      description: Specificando il nome del bot e caricando un file, si avvia l'addestramento per il singolo file
      operationId: addestramentoSingolo
      parameters:
        - name: nomeBot
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
        '500':
          description: Errore di sistema
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
  /documenti/addestramento-massivo:
    post:
      tags:
        - Documenti Controller
      summary: Addestamento massivo bot
      description: Specificando il nome del bot, si avvia l'addestramento massivo
      operationId: addestramentoMassivo
      parameters:
        - name: nomeBot
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
        '500':
          description: Errore di sistema
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
  /cartelle/rinomina:
    post:
      tags:
        - Cartelle Controller
      summary: Rinominare una cartella cartella
      description: Rinominare una cartella cartella e aggiornare i path dei file contenuti in essa
      operationId: rinominaCartella
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModificaCartellaParams'
        required: true
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoCartelleDto'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoCartelleDto'
  /ragbot/visualizza:
    get:
      tags:
        - Rag bot Controller
      summary: Elenco bot
      description: Elenco dei bot registrati nel database
      operationId: elencoBot
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoListRagBotPdfDto'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoListRagBotPdfDto'
  /cartelle/find:
    get:
      tags:
        - Cartelle Controller
      summary: Ritrovamento di una cartella
      description: Filtrare una cartella nel db
      operationId: findCartella
      parameters:
        - name: cartellaParams
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/CartellaParams'
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoCartelleDto'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoCartelleDto'
  /cartelle/elenco:
    get:
      tags:
        - Cartelle Controller
      summary: Elenco cartelle
      description: Elenco delle cartelle presenti nel db
      operationId: elencoCartelle
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoListCartelleDto'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoListCartelleDto'
  /ragbot/elimina:
    delete:
      tags:
        - Rag bot Controller
      summary: Elemina bot
      description: Elimina un bot nel database
      operationId: eliminaBot
      parameters:
        - name: nomeBot
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
  /cartelle/elimina:
    delete:
      tags:
        - Cartelle Controller
      summary: Eliminare una cartella cartella
      description: Eliminare una cartella cartella e i file contenuti in essa
      operationId: eliminaCartella
      parameters:
        - name: cartellaParams
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/CartellaParams'
      responses:
        '200':
          description: Operazione andata a buon fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
components:
  schemas:
    CartellaParams:
      type: object
      properties:
        nomeCartella:
          type: string
          description: Nome della cartella
        path:
          type: string
          description: Path delle cartella
        isCartellaAddestramento:
          type: boolean
          description: Path delle cartella
      description: CartellaParams
    CartelleDto:
      type: object
      properties:
        idCartella:
          type: integer
          format: int64
        nomeCartella:
          type: string
        path:
          type: string
        isCartellaAddestramento:
          type: boolean
    Esito:
      type: object
      properties:
        codRet:
          type: string
          enum:
            - OK
            - WARNING
            - KO
        operationId:
          type: string
        messaggi:
          type: array
          items:
            $ref: '#/components/schemas/Messaggio'
    GenericResponseDtoCartelleDto:
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/Esito'
        payload:
          $ref: '#/components/schemas/CartelleDto'
    Messaggio:
      type: object
      properties:
        severita:
          type: string
          enum:
            - INFO
            - WARNING
            - ERROR
            - PROPAGATED
        codMsg:
          type: string
        parametri:
          type: array
          items:
            $ref: '#/components/schemas/Parametro'
    Parametro:
      type: object
      properties:
        nome:
          type: string
        valore:
          type: string
    RegistraBotParams:
      type: object
      properties:
        nomeBot:
          type: string
          description: Path delle cartella
        descrizioneBot:
          type: string
          description: Path delle cartella
        urlSpring:
          type: string
          description: Path delle cartella
        urlPython:
          type: string
          description: Path delle cartella
        nomeCartellaAddestramento:
          type: string
          description: Path delle cartella
        nomeCartellaCaricamentoMassivo:
          type: string
          description: Path delle cartella
    GenericResponseDtoRagBotPdfDto:
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/Esito'
        payload:
          $ref: '#/components/schemas/RagBotPdfDto'
    RagBotPdfDto:
      type: object
      properties:
        idBot:
          type: integer
          format: int64
        nomeBot:
          type: string
        descrizioneBot:
          type: string
        urlSpring:
          type: string
        urlPython:
          type: string
        cartellaAddestramento:
          $ref: '#/components/schemas/CartelleDto'
        cartellaCaricamentoMassivo:
          $ref: '#/components/schemas/CartelleDto'
    ModificaBotParams:
      type: object
      properties:
        nomeBot:
          type: string
          description: Path delle cartella
        nuovoNomeBot:
          type: string
          description: Path delle cartella
        nuovaDescrizioneBot:
          type: string
          description: Path delle cartella
        nuovoUrlSpring:
          type: string
          description: Path delle cartella
        nuovoUrlPython:
          type: string
          description: Path delle cartella
        nuovoNomeCartellaAddestramento:
          type: string
          description: Path delle cartella
        nuovoNomeCartellaCaricamentoMassivo:
          type: string
          description: Path delle cartella
    GenericResponseDtoString:
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/Esito'
        payload:
          type: string
    ModificaCartellaParams:
      type: object
      properties:
        nuovoPath:
          type: string
          description: Nuovo path della cartella
        nuovoNomeCartella:
          type: string
          description: Nuovo nome della cartella
        nomeCartella:
          type: string
          description: Nome della cartella
        path:
          type: string
          description: Path delle cartella
        isCartellaAddestramento:
          type: boolean
          description: Path delle cartella
      description: ModificaCartellaParams
    GenericResponseDtoListRagBotPdfDto:
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/Esito'
        payload:
          type: array
          items:
            $ref: '#/components/schemas/RagBotPdfDto'
    GenericResponseDtoListCartelleDto:
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/Esito'
        payload:
          type: array
          items:
            $ref: '#/components/schemas/CartelleDto'
