/* tslint:disable */
/* eslint-disable */
/**
 * MS File Management
 * Microservizio dedicato alla gestione dei documenti e delle cartelle per l\'addestramento dei bot
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.calo29@studenti.uniba.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CartelleDto
 */
export interface CartelleDto {
    /**
     * 
     * @type {number}
     * @memberof CartelleDto
     */
    'idCartella'?: number;
    /**
     * 
     * @type {string}
     * @memberof CartelleDto
     */
    'nomeCartella'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartelleDto
     */
    'path'?: string;
}

