/* tslint:disable */
/* eslint-disable */
/**
 * MS File Management
 * Microservizio dedicato alla gestione dei documenti e delle cartelle per l\'addestramento dei bot
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.calo29@studenti.uniba.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EliminaDocumento
 * @export
 * @interface EliminaDocumento
 */
export interface EliminaDocumento {
    /**
     * Nome del file
     * @type {string}
     * @memberof EliminaDocumento
     */
    'nomeFile'?: string;
    /**
     * Path file
     * @type {string}
     * @memberof EliminaDocumento
     */
    'pathFile'?: string;
}

