/* tslint:disable */
/* eslint-disable */
/**
 * MS File Management
 * Microservizio dedicato alla gestione dei documenti e delle cartelle per l\'addestramento dei bot
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.calo29@studenti.uniba.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CartelleDto } from './cartelle-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { Esito } from './esito';

/**
 * 
 * @export
 * @interface GenericResponseDtoCartelleDto
 */
export interface GenericResponseDtoCartelleDto {
    /**
     * 
     * @type {Esito}
     * @memberof GenericResponseDtoCartelleDto
     */
    'esito'?: Esito;
    /**
     * 
     * @type {CartelleDto}
     * @memberof GenericResponseDtoCartelleDto
     */
    'payload'?: CartelleDto;
}

