/* tslint:disable */
/* eslint-disable */
/**
 * MS File Management
 * Microservizio dedicato alla gestione dei documenti e delle cartelle per l\'addestramento dei bot
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.calo29@studenti.uniba.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ModificaDocumentiParams
 * @export
 * @interface ModificaDocumentiParams
 */
export interface ModificaDocumentiParams {
    /**
     * Nome del file
     * @type {string}
     * @memberof ModificaDocumentiParams
     */
    'nomeFile'?: string;
    /**
     * Path del file
     * @type {string}
     * @memberof ModificaDocumentiParams
     */
    'pathFile'?: string;
    /**
     * Nuovo nome del file
     * @type {string}
     * @memberof ModificaDocumentiParams
     */
    'nuovoNome'?: string;
    /**
     * Nuovo path
     * @type {string}
     * @memberof ModificaDocumentiParams
     */
    'nuovoPath'?: string;
}

