/* tslint:disable */
/* eslint-disable */
/**
 * Applicativo BFF
 * Strato applicativo tramite il quale si fa interfacciare i vari microservizi BE con l\'applicativo FE
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.calo29@studenti.uniba.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Messaggio } from './messaggio';

/**
 * 
 * @export
 * @interface Esito
 */
export interface Esito {
    /**
     * 
     * @type {string}
     * @memberof Esito
     */
    'codRet'?: EsitoCodRetEnum;
    /**
     * 
     * @type {Array<Messaggio>}
     * @memberof Esito
     */
    'messaggi'?: Array<Messaggio>;
    /**
     * 
     * @type {string}
     * @memberof Esito
     */
    'operationId'?: string;
}

export const EsitoCodRetEnum = {
    Ok: 'OK',
    Warning: 'WARNING',
    Ko: 'KO'
} as const;

export type EsitoCodRetEnum = typeof EsitoCodRetEnum[keyof typeof EsitoCodRetEnum];


