/* tslint:disable */
/* eslint-disable */
/**
 * Applicativo BFF
 * Strato applicativo tramite il quale si fa interfacciare i vari microservizi BE con l\'applicativo FE
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.calo29@studenti.uniba.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CartelleDto } from './cartelle-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { Esito } from './esito';

/**
 * 
 * @export
 * @interface GenericResponseDtoListCartelleDto
 */
export interface GenericResponseDtoListCartelleDto {
    /**
     * 
     * @type {Esito}
     * @memberof GenericResponseDtoListCartelleDto
     */
    'esito'?: Esito;
    /**
     * 
     * @type {Array<CartelleDto>}
     * @memberof GenericResponseDtoListCartelleDto
     */
    'payload'?: Array<CartelleDto>;
}

