/* tslint:disable */
/* eslint-disable */
/**
 * Applicativo BFF
 * Strato applicativo tramite il quale si fa interfacciare i vari microservizi BE con l\'applicativo FE
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.calo29@studenti.uniba.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Parametro } from './parametro';

/**
 * 
 * @export
 * @interface Messaggio
 */
export interface Messaggio {
    /**
     * 
     * @type {string}
     * @memberof Messaggio
     */
    'severita'?: MessaggioSeveritaEnum;
    /**
     * 
     * @type {string}
     * @memberof Messaggio
     */
    'codMsg'?: string;
    /**
     * 
     * @type {Array<Parametro>}
     * @memberof Messaggio
     */
    'parametri'?: Array<Parametro>;
}

export const MessaggioSeveritaEnum = {
    Info: 'INFO',
    Warning: 'WARNING',
    Error: 'ERROR',
    Propagated: 'PROPAGATED'
} as const;

export type MessaggioSeveritaEnum = typeof MessaggioSeveritaEnum[keyof typeof MessaggioSeveritaEnum];


