/* tslint:disable */
/* eslint-disable */
/**
 * Applicativo BFF
 * Strato applicativo tramite il quale si fa interfacciare i vari microservizi BE con l\'applicativo FE
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.calo29@studenti.uniba.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModificaBotParams
 */
export interface ModificaBotParams {
    /**
     * Path delle cartella
     * @type {string}
     * @memberof ModificaBotParams
     */
    'nomeBot'?: string;
    /**
     * Path delle cartella
     * @type {string}
     * @memberof ModificaBotParams
     */
    'nuovoNomeBot'?: string;
    /**
     * Path delle cartella
     * @type {string}
     * @memberof ModificaBotParams
     */
    'nuovaDescrizioneBot'?: string;
    /**
     * Path delle cartella
     * @type {string}
     * @memberof ModificaBotParams
     */
    'nuovoUrlSpring'?: string;
    /**
     * Path delle cartella
     * @type {string}
     * @memberof ModificaBotParams
     */
    'nuovoUrlPython'?: string;
    /**
     * Path delle cartella
     * @type {string}
     * @memberof ModificaBotParams
     */
    'nuovoNomeCartellaAddestramento'?: string;
    /**
     * Path delle cartella
     * @type {string}
     * @memberof ModificaBotParams
     */
    'nuovoNomeCartellaCaricamentoMassivo'?: string;
}

