/* tslint:disable */
/* eslint-disable */
/**
 * Applicativo BFF
 * Strato applicativo tramite il quale si fa interfacciare i vari microservizi BE con l\'applicativo FE
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.calo29@studenti.uniba.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PdfAddestratiDto
 */
export interface PdfAddestratiDto {
    /**
     * 
     * @type {string}
     * @memberof PdfAddestratiDto
     */
    'nomeFile'?: string;
    /**
     * 
     * @type {string}
     * @memberof PdfAddestratiDto
     */
    'addestrato'?: string;
}

