/* tslint:disable */
/* eslint-disable */
/**
 * Applicativo BFF
 * Strato applicativo tramite il quale si fa interfacciare i vari microservizi BE con l\'applicativo FE
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.calo29@studenti.uniba.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CartelleDto } from './cartelle-dto';

/**
 * 
 * @export
 * @interface RagBotPdfDto
 */
export interface RagBotPdfDto {
    /**
     * 
     * @type {number}
     * @memberof RagBotPdfDto
     */
    'idBot'?: number;
    /**
     * 
     * @type {string}
     * @memberof RagBotPdfDto
     */
    'nomeBot'?: string;
    /**
     * 
     * @type {string}
     * @memberof RagBotPdfDto
     */
    'descrizioneBot'?: string;
    /**
     * 
     * @type {string}
     * @memberof RagBotPdfDto
     */
    'urlSpring'?: string;
    /**
     * 
     * @type {string}
     * @memberof RagBotPdfDto
     */
    'urlPython'?: string;
    /**
     * 
     * @type {CartelleDto}
     * @memberof RagBotPdfDto
     */
    'cartellaAddestramento'?: CartelleDto;
    /**
     * 
     * @type {CartelleDto}
     * @memberof RagBotPdfDto
     */
    'cartellaCaricamentoMassivo'?: CartelleDto;
}

