/* tslint:disable */
/* eslint-disable */
/**
 * Applicativo BFF
 * Strato applicativo tramite il quale si fa interfacciare i vari microservizi BE con l\'applicativo FE
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: f.calo29@studenti.uniba.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegistraBotParams
 */
export interface RegistraBotParams {
    /**
     * Path delle cartella
     * @type {string}
     * @memberof RegistraBotParams
     */
    'nomeBot'?: string;
    /**
     * Path delle cartella
     * @type {string}
     * @memberof RegistraBotParams
     */
    'descrizioneBot'?: string;
    /**
     * Path delle cartella
     * @type {string}
     * @memberof RegistraBotParams
     */
    'urlSpring'?: string;
    /**
     * Path delle cartella
     * @type {string}
     * @memberof RegistraBotParams
     */
    'urlPython'?: string;
    /**
     * Path delle cartella
     * @type {string}
     * @memberof RegistraBotParams
     */
    'nomeCartellaAddestramento'?: string;
    /**
     * Path delle cartella
     * @type {string}
     * @memberof RegistraBotParams
     */
    'nomeCartellaCaricamentoMassivo'?: string;
}

