/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GenericResponseDtoString } from '../model';
/**
 * CartelleControllerApi - axios parameter creator
 * @export
 */
export const CartelleControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} nomeCartella Nome della cartella
         * @param {string} path Path delle cartella
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aggiungiCartella: async (nomeCartella: string, path: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'nomeCartella' is not null or undefined
            assertParamExists('aggiungiCartella', 'nomeCartella', nomeCartella)
            // verify required parameter 'path' is not null or undefined
            assertParamExists('aggiungiCartella', 'path', path)
            const localVarPath = `/cartelle/crea`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nomeCartella !== undefined) {
                localVarQueryParameter['nomeCartella'] = nomeCartella;
            }

            if (path !== undefined) {
                localVarQueryParameter['path'] = path;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} nomeCartella Nome della cartella
         * @param {string} path Path delle cartella
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eliminaCartella: async (nomeCartella: string, path: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'nomeCartella' is not null or undefined
            assertParamExists('eliminaCartella', 'nomeCartella', nomeCartella)
            // verify required parameter 'path' is not null or undefined
            assertParamExists('eliminaCartella', 'path', path)
            const localVarPath = `/cartelle/elimina`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nomeCartella !== undefined) {
                localVarQueryParameter['nomeCartella'] = nomeCartella;
            }

            if (path !== undefined) {
                localVarQueryParameter['path'] = path;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} nuovoPath Nome della cartella
         * @param {string} nuovoNomeCartella Nome della cartella
         * @param {string} nomeCartella Nome della cartella
         * @param {string} path Path delle cartella
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rinominaCartella: async (nuovoPath: string, nuovoNomeCartella: string, nomeCartella: string, path: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'nuovoPath' is not null or undefined
            assertParamExists('rinominaCartella', 'nuovoPath', nuovoPath)
            // verify required parameter 'nuovoNomeCartella' is not null or undefined
            assertParamExists('rinominaCartella', 'nuovoNomeCartella', nuovoNomeCartella)
            // verify required parameter 'nomeCartella' is not null or undefined
            assertParamExists('rinominaCartella', 'nomeCartella', nomeCartella)
            // verify required parameter 'path' is not null or undefined
            assertParamExists('rinominaCartella', 'path', path)
            const localVarPath = `/cartelle/rinomina`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nuovoPath !== undefined) {
                localVarQueryParameter['nuovoPath'] = nuovoPath;
            }

            if (nuovoNomeCartella !== undefined) {
                localVarQueryParameter['nuovoNomeCartella'] = nuovoNomeCartella;
            }

            if (nomeCartella !== undefined) {
                localVarQueryParameter['nomeCartella'] = nomeCartella;
            }

            if (path !== undefined) {
                localVarQueryParameter['path'] = path;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CartelleControllerApi - functional programming interface
 * @export
 */
export const CartelleControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CartelleControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} nomeCartella Nome della cartella
         * @param {string} path Path delle cartella
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aggiungiCartella(nomeCartella: string, path: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericResponseDtoString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aggiungiCartella(nomeCartella, path, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartelleControllerApi.aggiungiCartella']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} nomeCartella Nome della cartella
         * @param {string} path Path delle cartella
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async eliminaCartella(nomeCartella: string, path: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericResponseDtoString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.eliminaCartella(nomeCartella, path, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartelleControllerApi.eliminaCartella']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} nuovoPath Nome della cartella
         * @param {string} nuovoNomeCartella Nome della cartella
         * @param {string} nomeCartella Nome della cartella
         * @param {string} path Path delle cartella
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rinominaCartella(nuovoPath: string, nuovoNomeCartella: string, nomeCartella: string, path: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericResponseDtoString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rinominaCartella(nuovoPath, nuovoNomeCartella, nomeCartella, path, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartelleControllerApi.rinominaCartella']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CartelleControllerApi - factory interface
 * @export
 */
export const CartelleControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CartelleControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {CartelleControllerApiAggiungiCartellaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aggiungiCartella(requestParameters: CartelleControllerApiAggiungiCartellaRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericResponseDtoString> {
            return localVarFp.aggiungiCartella(requestParameters.nomeCartella, requestParameters.path, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CartelleControllerApiEliminaCartellaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eliminaCartella(requestParameters: CartelleControllerApiEliminaCartellaRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericResponseDtoString> {
            return localVarFp.eliminaCartella(requestParameters.nomeCartella, requestParameters.path, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CartelleControllerApiRinominaCartellaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rinominaCartella(requestParameters: CartelleControllerApiRinominaCartellaRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericResponseDtoString> {
            return localVarFp.rinominaCartella(requestParameters.nuovoPath, requestParameters.nuovoNomeCartella, requestParameters.nomeCartella, requestParameters.path, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for aggiungiCartella operation in CartelleControllerApi.
 * @export
 * @interface CartelleControllerApiAggiungiCartellaRequest
 */
export interface CartelleControllerApiAggiungiCartellaRequest {
    /**
     * Nome della cartella
     * @type {string}
     * @memberof CartelleControllerApiAggiungiCartella
     */
    readonly nomeCartella: string

    /**
     * Path delle cartella
     * @type {string}
     * @memberof CartelleControllerApiAggiungiCartella
     */
    readonly path: string
}

/**
 * Request parameters for eliminaCartella operation in CartelleControllerApi.
 * @export
 * @interface CartelleControllerApiEliminaCartellaRequest
 */
export interface CartelleControllerApiEliminaCartellaRequest {
    /**
     * Nome della cartella
     * @type {string}
     * @memberof CartelleControllerApiEliminaCartella
     */
    readonly nomeCartella: string

    /**
     * Path delle cartella
     * @type {string}
     * @memberof CartelleControllerApiEliminaCartella
     */
    readonly path: string
}

/**
 * Request parameters for rinominaCartella operation in CartelleControllerApi.
 * @export
 * @interface CartelleControllerApiRinominaCartellaRequest
 */
export interface CartelleControllerApiRinominaCartellaRequest {
    /**
     * Nome della cartella
     * @type {string}
     * @memberof CartelleControllerApiRinominaCartella
     */
    readonly nuovoPath: string

    /**
     * Nome della cartella
     * @type {string}
     * @memberof CartelleControllerApiRinominaCartella
     */
    readonly nuovoNomeCartella: string

    /**
     * Nome della cartella
     * @type {string}
     * @memberof CartelleControllerApiRinominaCartella
     */
    readonly nomeCartella: string

    /**
     * Path delle cartella
     * @type {string}
     * @memberof CartelleControllerApiRinominaCartella
     */
    readonly path: string
}

/**
 * CartelleControllerApi - object-oriented interface
 * @export
 * @class CartelleControllerApi
 * @extends {BaseAPI}
 */
export class CartelleControllerApi extends BaseAPI {
    /**
     * 
     * @param {CartelleControllerApiAggiungiCartellaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartelleControllerApi
     */
    public aggiungiCartella(requestParameters: CartelleControllerApiAggiungiCartellaRequest, options?: RawAxiosRequestConfig) {
        return CartelleControllerApiFp(this.configuration).aggiungiCartella(requestParameters.nomeCartella, requestParameters.path, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CartelleControllerApiEliminaCartellaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartelleControllerApi
     */
    public eliminaCartella(requestParameters: CartelleControllerApiEliminaCartellaRequest, options?: RawAxiosRequestConfig) {
        return CartelleControllerApiFp(this.configuration).eliminaCartella(requestParameters.nomeCartella, requestParameters.path, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CartelleControllerApiRinominaCartellaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartelleControllerApi
     */
    public rinominaCartella(requestParameters: CartelleControllerApiRinominaCartellaRequest, options?: RawAxiosRequestConfig) {
        return CartelleControllerApiFp(this.configuration).rinominaCartella(requestParameters.nuovoPath, requestParameters.nuovoNomeCartella, requestParameters.nomeCartella, requestParameters.path, options).then((request) => request(this.axios, this.basePath));
    }
}

