/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GenericResponseDtoString } from '../model';
/**
 * DocumentiControllerApi - axios parameter creator
 * @export
 */
export const DocumentiControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} uploadDir 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFile: async (uploadDir: string, file: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uploadDir' is not null or undefined
            assertParamExists('uploadFile', 'uploadDir', uploadDir)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadFile', 'file', file)
            const localVarPath = `/documenti/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            if (uploadDir !== undefined) {
                localVarQueryParameter['uploadDir'] = uploadDir;
            }


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DocumentiControllerApi - functional programming interface
 * @export
 */
export const DocumentiControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DocumentiControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} uploadDir 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFile(uploadDir: string, file: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericResponseDtoString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadFile(uploadDir, file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DocumentiControllerApi.uploadFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DocumentiControllerApi - factory interface
 * @export
 */
export const DocumentiControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DocumentiControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {DocumentiControllerApiUploadFileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFile(requestParameters: DocumentiControllerApiUploadFileRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericResponseDtoString> {
            return localVarFp.uploadFile(requestParameters.uploadDir, requestParameters.file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for uploadFile operation in DocumentiControllerApi.
 * @export
 * @interface DocumentiControllerApiUploadFileRequest
 */
export interface DocumentiControllerApiUploadFileRequest {
    /**
     * 
     * @type {string}
     * @memberof DocumentiControllerApiUploadFile
     */
    readonly uploadDir: string

    /**
     * 
     * @type {File}
     * @memberof DocumentiControllerApiUploadFile
     */
    readonly file: File
}

/**
 * DocumentiControllerApi - object-oriented interface
 * @export
 * @class DocumentiControllerApi
 * @extends {BaseAPI}
 */
export class DocumentiControllerApi extends BaseAPI {
    /**
     * 
     * @param {DocumentiControllerApiUploadFileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentiControllerApi
     */
    public uploadFile(requestParameters: DocumentiControllerApiUploadFileRequest, options?: RawAxiosRequestConfig) {
        return DocumentiControllerApiFp(this.configuration).uploadFile(requestParameters.uploadDir, requestParameters.file, options).then((request) => request(this.axios, this.basePath));
    }
}

